name: manzanitas.co
favicon: null
layout_spectrum: 0
typography_spectrum: 0.10597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5737470090389252
  lightness: 0.8645819616504014
  saturation: 0.5036427832674235
  rhythmicContrast: 0.7154668648727238
purpose: []
